image: node:latest

variables: {}

# Cache modules in between jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

before_script:
  # Fix Git Imports
  - "git config --global url.https://gitlab.com/.insteadOf git@gitlab.com:"
  - git submodule init
  - git submodule update
  - npm ci

build_style_guide:
  script:
  - npm run-script styleguide-build
  artifacts:
    paths:
    - build/styleguide
