image: node:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

# Cache modules in between jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

before_script:
  - npm ci

lint:
  script:
    - npm run-script lint

build_style_guide:
  script:
  - npm run-script styleguide-build
  artifacts:
    paths:
    - build/styleguide
